apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-points-cron
spec:
  schedule: 0 * * * *
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - command:
                - /opt/mssql-tools/bin/sqlcmd
                - -S
                - $(DB_SERVER)
                - -U
                - $(DB_USERNAME)
                - -P
                - $(DB_PASSWORD)
                - -d
                - $(DB_NAME)
                - -Q
                - EXEC dbo.spUpdateRankings
              image: mcr.microsoft.com/mssql-tools
              imagePullPolicy: IfNotPresent
              name: {{ .Chart.Name }}-points-cron
              envFrom:
                - secretRef:
                    name: {{ .Release.Name }}-config
          restartPolicy: Never
