apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-config
type: Opaque
stringData:
  {{- toYaml .Values.config.server | nindent 2 }}
---
{{- if contains "File" .Values.signing.type}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-signing
type: Opaque
data:
  signing.pfx: {{ .Values.signing.pfx }}
stringData:
  password: {{ .Values.signing.password | quote }}
{{- end }}